---
- hosts: all
  become: true

  vars:
    ansible_python_interpreter: '/usr/local/bin/python2.7'

  tasks:
    - include_role:
        name: 'JoergFiedler.freebsd-jailed'
      vars:
        jail_net_ip: '10.1.0.10'
        jail_name: 'jailed'
        use_ssmtp: true
      tags:
        - _jailed
