- debug: msg='Running tasks for jail {{ jail_name }}'

- name: Check if jail already exists
  command: |
    /usr/local/bin/iocage get boot {{ jail_name }}
  ignore_errors: yes
  changed_when: false
  register: jail_exists

- name: Create jail
  command: |
    /usr/local/bin/iocage create \
      --name {{ jail_name }} \
      --release {{ jail_freebsd_release }}
  when: jail_exists is failed
  register: jail_created
  notify:
    - Start iocage

- name: Set jail properties
  command: |
    /usr/local/bin/iocage set {{ item }} {{ jail_name }}
  loop:
    - 'boot=on'
    - 'vnet=off'
    - 'resolver={{ jail_net_resolver }}'
    - 'ip4_addr=lo0|{{ jail_net_ip }}/32'
  when: jail_created is changed

- name: Register home diretory
  command: |
    echo {{ host_ioc_jails_dir }}/{{ jail_name }}/root
  changed_when: false
  register: jail_home

- name: Copy default resolv.conf
  copy:
    backup: '{{ jail_backup_old_files }}'
    src: '/etc/resolv.conf'
    dest: '{{ jail_home.stdout }}/etc/resolv.conf'
    remote_src: true
  when: jail_created is changed

- name: Update resolv.conf
  replace:
    backup: '{{ jail_backup_old_files }}'
    path: '{{ jail_home.stdout }}/etc/resolv.conf'
    regexp: '(nameserver\s+).*$'
    replace: '\1{{ jail_net_resolver }}'
  when: jail_net_resolver != 'none'
