---
- debug: msg='Running tasks for jail {{ jail_name }}'

- name: Check if jail already exists
  shell: /usr/local/bin/iocage get boot {{ jail_name }}
  ignore_errors: true
  changed_when: false
  register: jail_exists

- name: Create jail
  command: /usr/local/bin/iocage create \
    --name {{ jail_name }} \
    --release {{ jail_freebsd_release }}
  when: jail_exists | failed
  register: jail_created
  notify:
    - Start iocage

- name: Set jail properties
  command: /usr/local/bin/iocage set {{ item }} {{ jail_name }}
  with_items:
    - 'boot=on'
    - 'vnet=off'
    - 'ip4_addr=lo0|{{ jail_net_ip }}/32'
  when: jail_created | changed

- name: Register home diretory
  command: echo {{ host_ioc_jails_dir }}/{{ jail_name }}/root
  changed_when: false
  register: jail_home

