- import_tasks: iocage.yml
  tags:
    - jailed
- import_tasks: net.yml
  tags:
    - jailed
- import_tasks: repo.yml
  tags:
    - jailed
  when:  jail_build_server_enabled | default(false)
- import_tasks: pf.yml
  tags:
    - jailed
- import_tasks: user.yml
  tags:
    - jailed
- import_tasks: timezone.yml
  tags:
    - jailed
- import_tasks: syslogd-client.yml
  tags:
    - jailed
  when: use_syslogd_server | default(false)
- import_tasks: ssmtp.yml
  tags:
    - jailed
  when: use_ssmtp | default(false)
