- name: Install root certificate authorities
  pkgng:
    name: 'ca_root_nss'
    state: present
    chroot: '{{ jail_home.stdout }}'
  register: pkg_result
  until: pkg_result is succeeded

- name: Add network config
  lineinfile:
    backup: '{{ jail_backup_old_files }}'
    dest: '/etc/rc.conf'
    state: present
    line: '{{ ifconfig_net_if_line }}'
  notify: Activate network config
