- name: Add network config
  lineinfile:
    backup: '{{ jail_backup_old_files }}'
    dest: '/etc/rc.conf'
    state: present
    line: '{{ ifconfig_net_if_line }}'
  notify: Activate network config
