- name: Reload {{ jail_name }} s syslogd
  command: |
    /usr/local/bin/iocage exec {{ jail_name }} service syslogd reload
  when: not jail_created is changed

- name: Activate network config
  command: |
    ifconfig {{ jail_net_if }} inet alias {{ jail_net_ip }} netmask 255.255.255.255
